### ISSUE TITLE
Algorithm Research

### ISSUE THREAD

**Issue by Kydoimos97** [Kydoimos97/CapstoneMSBA2020#27]
[5_time_series.pdf](https://github.com/Kydoimos97/CapstoneMSBA2020/files/6013965/5_time_series.pdf)

**Comment by Kydoimos97** [comment]
Consider Running Auto Arima in R

**Comment by Kydoimos97** [comment]
[Uploading Var Model TWDSDS.pdf…]()

**Comment by Kydoimos97** [comment]
[Var Model TWDSDS.pdf](https://github.com/Kydoimos97/CapstoneMSBA2020/files/6214898/Var.Model.TWDSDS.pdf)

**Comment by sammer21** [comment]
Found this interesting article as well that could be helpful with the Arima model and dealing with seasonal data.

https://towardsdatascience.com/time-series-in-python-part-2-dealing-with-seasonal-data-397a65b74051

**Comment by Kydoimos97** [comment]
Problems with the data set size can be solved by splitting the data sets on Site_Id's

**Comment by Kydoimos97** [comment]
Start focussing on VAR model.

[link](https://online.stat.psu.edu/stat510/lesson/11/11.2)

**Comment by sammer21** [comment]
For the evaluation step in the VAR method it has us use a method called FEVD. FEVD means Forecast Error Variance Decomposition. It is used to aid in the interpretation of a VAR model once it has been fitted. 

The variance decomposition indicates the amount of information each variable contributes to the other variables in the autoregression. It determines how much of the forecast error variance of each of the variables can be explained by exogenous shocks to the other variables.

**Comment by Kydoimos97** [comment]
Finished all needed research
