### ISSUE TITLE
Data Cleaning in Python

### ISSUE THREAD

**Issue by Kydoimos97** [Kydoimos97/CapstoneMSBA2020#31]

**Comment by Kydoimos97** [comment]
1. Temprature Imputation
2. Remove Project and coerce to a new dataset
3. Outliers 
4. Remove some columns?
5. Add Sales

**Comment by kelsey-codes** [comment]
Temp Imputation complete: see closed NA issue for more details

**Comment by Kydoimos97** [comment]
> 1. Temprature Imputation
> 2. Remove Project and coerce to a new dataset
> 3. Outliers
> 4. Remove some columns?
> 5. Add Sales

It's all done.
Check the File [Here](https://github.com/Kydoimos97/CapstoneMSBA2020/blob/main/PythonCode/DataCleaning/Python_CleaningPDF.pdf)

**Comment by Kydoimos97** [comment]
I'll close the topic now, if you reviewed and have questions feel free to reopen the topic.
