### ISSUE TITLE
ARIMA and Dickey Fuller Test 

### ISSUE THREAD

**Issue by sammer21** [Kydoimos97/CapstoneMSBA2020#32]
Run a Dickey Fuller test on the cleaned Python file that Willem has updated.

**Comment by Kydoimos97** [comment]
Refer to this Issue: #27

**Comment by Kydoimos97** [comment]
Sorted Out in [deliverables](https://github.com/Kydoimos97/CapstoneMSBA2020/blob/main/PythonCode/Maverick%20Applet.py)
