### ISSUE TITLE
Write Manual Lag Code in Python

### ISSUE THREAD

**Issue by Kydoimos97** [Kydoimos97/CapstoneMSBA2020#34]

**Comment by timgain** [comment]
Just want to make sure I'm understanding what we are looking for before I start trying to answer the wrong question.  I think I recall Jeff saying we should do a 7-day lag.  So I'm assuming there would be new column "7_day_lag" with the value for today (Wednesday 3/31) showing the sales number for last Wednesday 3/24?

**Comment by Kydoimos97** [comment]
Honestly any day lag is fine. Jeff talked about 7 days, 1 day, 365 days lag. So lag needs to be an input in a function or loop that we can adjust.

**Comment by timgain** [comment]
Still not right, but wanted to show what I have so far:

df = df.sort_values('date', axis=0, ascending=True)
df["prior_week_sales"] = df.groupby(['date'])['sales'].shift(7)
df.head(30)

This does lag the Sales amount by 7 rows, but I still haven't found how to make it shift by an entire day rather than just by a set number of rows.  Not all days have the same number of rows, so we can't just use .shift(500) or something like that.  Still working on it.

**Comment by Kydoimos97** [comment]
![image](https://user-images.githubusercontent.com/63725110/113460250-3d423b80-93d5-11eb-83ec-18a78472b191.png)

**Comment by Kydoimos97** [comment]
```



import time

lag = 7
days = 86400
counter = 0
timeA = time.time()
timediff2= 0
counterdiff = 100

for i in range(0,len(df)) :
    
    date_t = df.loc[i,'date']
    item_id_t = df.loc[i,'item_id']
    site_id_t = df.loc[i,'site_id']
    
    date_lagged = pd.Timestamp(df.loc[i,'date'].timestamp() - (lag*days), unit='s')
    
    sub = df.loc[(df['date']==date_lagged) & (df['site_id']== site_id_t) & (df['item_id'] == item_id_t)]
    
    if len(sub) > 0:
        df.loc[i,'lag_sales'] = sub.iloc[0,5]
    else:
        df.loc[i,'lag_sales'] =  0
        
    if i%int(len(df)/counterdiff) == 0:
        if counter == 0:
            counter = counter+1 
            print("===Initializing===")
        else:
            timeB = time.time()
            timediff = timeB-timeA
            timediff2 = timediff2+timediff
            print("Progress =", counter/(counterdiff/100),"% | ",
                  "Time Elapsed = ", round(timediff2,2), 
                  " Seconds | ", "Est. Time Remaining = ", round(timediff*(counterdiff-counter),2), " Seconds" )
            counter = counter+1
            timeA = time.time()
    else: 
        pass
```
