### ISSUE TITLE
Process / Error Log

### ISSUE THREAD

**Issue by Kydoimos97** [Kydoimos97/CapstoneMSBA2020#38]
Log your process and errors here.

**Comment by Kydoimos97** [comment]
![image](https://user-images.githubusercontent.com/63725110/113463769-1a1f8800-93e5-11eb-9d60-0c104c78fec0.png)

**Comment by sammer21** [comment]
![Error](https://user-images.githubusercontent.com/62916608/114249887-22ce0c00-9959-11eb-94db-db75ce38a4aa.PNG)

**Comment by Kydoimos97** [comment]
Loop Update: 

![image](https://user-images.githubusercontent.com/63725110/114251612-e0a7c900-995e-11eb-948a-22f8d64a63af.png)


``
import time

lag = 7
days = 86400
counter = 0
timeA = time.time()
timediff2= 0
counterdiff = 1000
lag_list = list()

for i in range(0,len(df)) :
    
    date_t = df.loc[i,'date']
    item_id_t = df.loc[i,'item_id']
    site_id_t = df.loc[i,'site_id']
    
    date_lagged = pd.Timestamp(df.loc[i,'date'].timestamp() - (lag*days), unit='s')
    
    sub = df.loc[(df['date']==date_lagged) & (df['site_id']== site_id_t) & (df['item_id'] == item_id_t)].reset_index(drop=True)
    
    if len(sub) > 0:
        df.loc[i,'lag_sales'] = sub.loc[0,'sales']
        lag_list.append(sub.loc[0,'sales'])
    else:
        df.loc[i,'lag_sales'] =  0
        lag_list.append(0)
        
    if i%int(len(df)/counterdiff) == 0:
        if counter == 0:
            counter = counter+1 
            print("===Initializing===")
        elif i == int(len(df)):
            timeB = time.time()
            timediff = timeB-timeA
            timediff2 = timediff2+timediff
            print("Progress =", counter/(counterdiff/100),"% | ",
                  "Time Elapsed = ", round(timediff2,2), " Seconds | ",)
        else:
            timeB = time.time()
            timediff = timeB-timeA
            timediff2 = timediff2+timediff
            print("Progress =", counter/(counterdiff/100),"% | ",
                  "Time Elapsed = ", round(timediff2,2), 
                  " Seconds | ", "Est. Time Remaining = ", round(timediff*(counterdiff-counter),2), " Seconds" )
            counter = counter+1
            timeA = time.time()
    else: 
        pass

del(i, lag, days, counter, counterdiff, dfsub, date_t, item_id_t, site_id_t, date_lagged, sub,timeA,timeB,timediff,timediff2)
``

**Comment by sammer21** [comment]
VAR Method: 
`from sklearn.model_selection import train_test_split

#split data into train and test
train, test = train_test_split(df_acf)

#model fitting
model = VAR(train)
results = model.fit(maxlags = 15, ic = 'aic')
results.summary()

#forecasting
lag_order = results.k_ar
results.forecast(df_acf.values[-lag_order:], 5)

results.plot_forecast(20)

#Evaluate
fevd = results.fevd(5)
display(fevd.summary())

`

**Comment by Kydoimos97** [comment]
Consider Items in the Item List only for now. 

Here are the reasons why:

[](https://en.wikipedia.org/wiki/Pareto_principle)

![image](https://user-images.githubusercontent.com/63725110/114253061-ad1c6d00-9965-11eb-92c7-680d1dec95cf.png)
