### ISSUE TITLE
Algorithm Research

### ISSUE THREAD

**Issue by Kydoimos97** [Kydoimos97/CapstoneMSBA2020#8]
Using a standard GLM algorithm, I could not predict a single value correctly. We need someone to do research into time-series analysis and start coming up with a plan for how we are going to tackle this. I assume we need to aggregate a number of things because the dataset itself is confusing. There are time series but they are not properly displayed and conveyed to the algorithm causing deviance as shown in the screenshot.

![image](https://user-images.githubusercontent.com/63725110/107624490-33dbf480-6c18-11eb-9063-b50de71ab3b7.png)

**Comment by sammer21** [comment]
Sounds good. We should look into the benefits of time series in Python vs R and see which would be most beneficial. I'd be happy to do some research on this and see what would be best for us.

**Comment by Kydoimos97** [comment]
Everyone needs to go through algorithms and decide for their selves what they would use so we can discuss this and come to an agreement next week.

**Comment by Kydoimos97** [comment]
I did some research regarding time series forecasting these are my results. They are pretty good I am happy with them but they are on full store levels so not fully like the assignment described.

![image](https://user-images.githubusercontent.com/63725110/108577613-e8dc7400-72de-11eb-86b9-45d7b4584a86.png)

![image](https://user-images.githubusercontent.com/63725110/108577627-eed25500-72de-11eb-8810-4075000f68cb.png)

**Comment by sammer21** [comment]
Hey everyone. I've been researching up on time series methods in R and Python looking at the packages they have available for us to use. The best algorithm for us to use in our case would be the ARIMA model. This is used from the statsmodels package in Python using the adfuller() function or the stats package in R using the arima() function. I would recommend we still stick with Python however as the adfuller() function seems very slick and easy to use. I found this article about how to create an ARIMA sales forecasting model [here](https://www.analyticsvidhya.com/blog/2020/10/how-to-create-an-arima-model-for-time-series-forecasting-in-python/). It is a good reference for us about the process of setting it up, checking for stationarity, and how to solve the model. This is the model I would recommend and seems to best fit our needs. I'll do some more digging to help us find other good examples but I think this should give us a good head start. 

Let me know your thoughts. Thanks.

**Comment by Kydoimos97** [comment]
Linked to #27

**Comment by Kydoimos97** [comment]
Linked to #27
