### ISSUE TITLE
Cleaning the variables and NA's in temprature 

### ISSUE THREAD

**Issue by Kydoimos97** [Kydoimos97/CapstoneMSBA2020#9]
The NA's in temperature is a problem since no location data is present. We need people to dive into how we are either going to impute, bootstrap, or remove this data from the data set.

![image](https://user-images.githubusercontent.com/63725110/107624786-992fe580-6c18-11eb-9cc8-68f16a72955c.png)

**Comment by sammer21** [comment]
Let's talk tonight in our meeting about the value of temperature to the overall analysis and if this is a key variable we need to keep.

**Comment by kelsey-codes** [comment]
From Maverik: Given that a relatively accurate 10 forecast and an even more accurate 5-7 day forecast is available from various weather services, we would use that data to forecast sales. If it helps, these stores are located in Utah County. You can use the historical temperature data for that county in your analysis.

**Comment by Kydoimos97** [comment]
> From Maverik: Given that a relatively accurate 10 forecast and an even more accurate 5-7 day forecast is available from various weather services, we would use that data to forecast sales. 

If anyone can figure out an API that is free and works for us during this project we can close this topic afterward.

**Comment by kelsey-codes** [comment]
https://rapidapi.com/blog/access-global-weather-data-with-these-weather-apis/ 
8 free APIs

**Comment by Kydoimos97** [comment]
> https://rapidapi.com/blog/access-global-weather-data-with-these-weather-apis/
> 8 free APIs

Nice website; thank you, Kelsey! I quickly checked, and we likely want to use: [weatherbit](https://rapidapi.com/weatherbit/api/weather?endpoint=apiendpoint_6d494085-df7b-4efe-8f42-209851a6f9a5)  for their 16-day forecast and [Visual Crossing](https://rapidapi.com/visual-crossing-corporation-visual-crossing-corporation-default/api/visual-crossing-weather?endpoint=apiendpoint_e007826d-743d-4edd-bcee-f4a8e545e4a8) for their historical data. The visual crossing only allows a 7-day forecast, and weatherbit doesn't show historical data. These two are also completely free, with the highest query limits per day.

**Comment by kelsey-codes** [comment]
Python Functions for imputing NAs for Time Series 

https://drnesr.medium.com/filling-gaps-of-a-time-series-using-python-d4bfddd8c460

https://towardsdatascience.com/multivariate-time-series-forecasting-653372b3db36

https://stackoverflow.com/questions/49308530/missing-values-in-time-series-in-python

https://www.dezyre.com/recipes/deal-with-missing-values-in-timeseries-in-python

**Comment by Kydoimos97** [comment]
```
df['mintemp'].interpolate(method='linear', inplace=True)    
df['maxtemp'].interpolate(method='linear', inplace=True)   
```

Before: 
![image](https://user-images.githubusercontent.com/63725110/111694602-b3507b00-87f7-11eb-8b3d-2ce698398c2c.png)

After:
![image](https://user-images.githubusercontent.com/63725110/111694615-b8152f00-87f7-11eb-8a59-c199fcdbb4f0.png)
